chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("api/create-room/<str:uuid>/", views.create_room, name="create-room"),
    path("chat-admin/", views.admin, name="admin"),
    path("chat-admin/add-user/", views.add_user, name="add_user"),
    path("chat-admin/users/<uuid:uuid>/", views.user_detail, name="user_detail"),
    path("chat-admin/users/<uuid:uuid>/edit/", views.edit_user, name="edit_user"),
    path("chat-admin/<str:uuid>/", views.room, name="room"),
    path("chat-admin/<str:uuid>/delete/", views.delete_room, name="delete_room"),
]

jatte/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

chat/models.py
from django.db import models

from account.models import User


class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.SET_NULL
    )

    class Meta:
        ordering: "created_at"

    def __str__(self):
        return f"{self.sent_by}"


class Room(models.Model):

    WAITING = "waiting"
    ACTIVE = "active"
    CLOSED = "closed"

    CHOICES_STATUS = [(WAITING, "Waiting"), (ACTIVE, "Active"), (CLOSED, "Closed")]

    uuid = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(
        User, related_name="rooms", blank=True, null=True, on_delete=models.SET_NULL
    )
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering: ["-created_at"]

    def __str__(self):
        return f"{self.client} - {self.uuid}"

chat/views.py
import json

# Django modules for handling authentication, permissions, messages, and HTTP responses
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt

# Importing custom user model and forms
from account.models import User
from account.forms import AddUserForm, EditUserForm

# Importing the Room model
from .models import Room

# Redundant import, already imported above
from django.shortcuts import render


# API view to create a chat room
@csrf_exempt  # Disables CSRF validation – only use in testing, not production!
@require_POST  # Ensures the view only handles POST requests
def create_room(request, uuid):
    # Get room name and URL from POST data
    name = request.POST.get("name", "")
    url = request.POST.get("url", "")

    # Create a new Room instance in the database
    Room.objects.create(uuid=uuid, client=name, url=url)

    # Return success response as JSON
    return JsonResponse({"message": "room created"})


# Admin panel view, shows all rooms and staff users
@login_required  # Requires user to be logged in
def admin(request):
    rooms = Room.objects.all().order_by("-created_at")  # Get all chat rooms
    users = User.objects.filter(is_staff=True)  # Get all staff users

    # Render admin template with room and user data
    return render(request, "chat/admin.html", {"rooms": rooms, "users": users})


# Chat room view
@login_required
def room(request, uuid):
    # Get the specific room by UUID
    room = Room.objects.get(uuid=uuid)

    if room.status == Room.WAITING:
        room.status = Room.ACTIVE
        room.agent = request.user
        room.save()

    # Render the room template with the room object
    return render(request, "chat/room.html", {"room": room})


# Chat room delete
@login_required
def delete_room(request, uuid):
    if request.user.has_perm("room.delete_room"):
        # Get the specific room by UUID
        room = Room.objects.get(uuid=uuid)
        room.delete()

        messages.success(request, "The room was deleted")
        return redirect("/chat-admin/")
    else:
        # If user doesn't have permission, show error and redirect
        messages.error(request, "You don't have access to delete users!")
        return redirect("/chat-admin/")


@login_required
def user_detail(request, uuid):
    user = User.objects.get(pk=uuid)
    rooms = user.rooms.all()
    return render(
        request,
        "chat/user_detail.html",
        {
            "user": user,
            "rooms": rooms,
        },
    )


# edit user
@login_required
def edit_user(request, uuid):
    # Check if current user has permission to add users
    if request.user.has_perm("user.edit_user"):
        user = User.objects.get(pk=uuid)

        if request.method == "POST":
            form = EditUserForm(request.POST, instance=user)

            if form.is_valid:
                form.save()

                messages.success(request, "The changes were saved")
                return redirect("/chat-admin/")
        else:
            form = EditUserForm(instance=user)

        return render(
            request,
            "chat/edit_user.html",
            {
                "user": user,
                "form": form,
            },
        )

    else:
        # If user doesn't have permission, show error and redirect
        messages.error(request, "You don't have access to edit users!")
        return redirect("/chat-admin/")


# Add new user view (only if user has permission)
@login_required
def add_user(request):
    # Check if current user has permission to add users
    if request.user.has_perm("user.add_user"):
        print("***Begin adding user...")
        if request.method == "POST":
            form = AddUserForm(request.POST)  # Populate form with POST data
            print("***form...", form)

            print(request.POST)

            if form.is_valid():
                print("***form.is_valid...")
                user = form.save(
                    commit=False
                )  # Create user object without saving to DB yet
                user.is_staff = True  # Set user as staff

                password = request.POST.get("password")
                if password:
                    user.set_password(password)
                else:
                    messages.error(request, "Password is required.")
                    return render(request, "chat/add_user.html", {"form": form})

                user.save()  # Save user to database

                # Add user to "Managers" group if their role is MANAGER
                if user.role == User.MANAGER:
                    try:
                        group = Group.objects.get(name="Managers")
                        group.user_set.add(user)
                    except Group.DoesNotExist:
                        messages.warning(
                            request,
                            "Manager group does not exist. User not added to group.",
                        )

                # Show success message
                messages.success(request, "The user was added!!")
                return redirect("chat:admin")  # <--- redirect to the admin page

            else:
                messages.error(request, "Form is invalid. Please check the input.")
                return render(request, "chat/add_user.html", {"form": form})

        else:
            form = AddUserForm()  # If GET request, show empty form

        # Render add user form
        return render(request, "chat/add_user.html", {"form": form})
    else:
        # If user doesn't have permission, show error and redirect
        messages.error(request, "You don't have access to add users!")
        return redirect("/chat-admin/")

chat/templates/chat/partials/chat_bubble.html
<div
  id="chat"
  class="max-w-[300px] fixed right-2 bottom-2 p-0 bg-white border border-gray-100 rounded-lg shadow-lg"
>
  <!-- chat icon -->
  <div id="chat_icon" class="flex items-center justify-center">
    <button
      id="chat_open"
      class="w-[50px] h-[50px] flex items-center text-center p-2"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        stroke="currentColor"
        class="text-indigo-600"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M8.625 9.75a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm0 0H8.25m4.125 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm0 0H12m4.125 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 0 1 .778-.332 48.294 48.294 0 0 0 5.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0 0 12 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018Z"
        />
      </svg>
    </button>
  </div>

  <!-- welcome to chat -->
  <div id="chat_welcome" class="hidden relative">
    <!-- close button -->
    <button
      id="chat_close"
      class="w-5 h-5 opacity-75 text-white text-xs rounded-full absolute top-2 right-2"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        stroke="currentColor"
        class="size-6"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
        />
      </svg>
    </button>

    <!-- begin welcome -->
    <div
      class="text-white bg-gradient-to-br from-purple-600 to-blue-500 font-medium text-sm px-5 py-2.5 text-center rounded-t-lg"
    >
      <p class="text-xl">Let's Chat</p>
    </div>

    <div class="py-3 px-5">
      <div>
        <p class="text-gray-800 text-md font-medium">
          We'd love to get to know you
        </p>
        <p class="text-gray-500 text-xs font-light mt-1">
          Please share your name before we begin chatting! 😊
        </p>
      </div>

      <!-- input name -->
      <div class="relative mt-3 mb-4">
        <input
          type="text"
          id="chat_name"
          class="block rounded-t-lg px-2.5 pb-2.5 pt-5 w-full text-sm text-gray-900 bg-gray-50 dark:bg-gray-700 border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
          placeholder=" "
        />
        <label
          for="chat_name"
          class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-4 z-10 origin-[0] start-2.5 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-4 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto"
          >your name</label
        >
      </div>

      <!-- join button -->
      <button
        id="chat_join"
        type="button"
        class="text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
      >
        Join Chat
      </button>
    </div>
  </div>

  <!-- chat room -->
  <div id="chat_room" class="hidden">
    <!-- <div id="chat_log" class="w-full mb-4 p-4 rounded-md h-[300px] overflow-scroll bg-rose-400"> -->

    <!-- header -->
    <div
      class="text-white bg-gradient-to-br from-purple-600 to-blue-500 font-medium text-sm px-5 py-2.5 text-center rounded-t-lg"
    >
      <p class="text-xl">Let's Chat</p>
    </div>

    <!-- log -->
    <div class="p-2">

      <div
        id="chat_log"
        class="w-full min-w-[284px] h-[300px] mb-2 p-2 rounded-md overflow-auto bg-gray-50"
      >
        <!-- alert -->
        <div
          id="chat_log_alert"
          class="flex items-center p-4 mb-4 text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400"
          role="alert"
        >
          <svg
            class="shrink-0 w-4 h-4"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 20 20"
          >
            <path
              d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"
            />
          </svg>
          <span class="sr-only">Info</span>
          <div class="ms-3 text-xs font-medium">
            Welcome to our chat! Please type your message and wait for an agent
            to join...
          </div>
          <button
            type="button"
            class="ms-auto -mx-1.5 -my-1.5 bg-blue-50 text-blue-500 rounded-lg focus:ring-2 focus:ring-blue-400 p-1.5 hover:bg-blue-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-blue-400 dark:hover:bg-gray-700"
            data-dismiss-target="#chat_log_alert"
            aria-label="Close"
          >
            <span class="sr-only">Close</span>
            <svg
              class="w-3 h-3"
              aria-hidden="true"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 14 14"
            >
              <path
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"
              />
            </svg>
          </button>
        </div>
        
      </div>

      <!-- text message -->
      <div class="relative mt-3 mb-4">
        <input
          type="text"
          id="chat_message_input"
          class="block rounded-t-lg px-2.5 pb-2.5 pt-5 w-full text-sm text-gray-900 bg-gray-50 dark:bg-gray-700 border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
          placeholder=" "
        />
        <label
          for="chat_name"
          class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-4 z-10 origin-[0] start-2.5 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-4 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto"
          >your message</label
        >
      </div>

      <!-- send message -->
      <button
        id="chat_message_submit"
        class="text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 disabled:hover:cursor-not-allowed disabled:bg-gray-100"
      >
        Send
      </button>
    </div>
  </div>
</div>

chat/templates/chat/partials/room_list.html
<div class="grid grid-cols-4 gap-4">
  {% for room in rooms %}
  <div
    class="rounded-xl {% if room.status == 'active' %} bg-indigo-50 {% elif room.status == 'waiting' %} bg-fuchsia-50 {% else %} bg-gray-50 {% endif %} shadow-md"
  >
    <!-- top of the card -->
    <div
      class="relative h-3 rounded-t-xl {% if room.status == 'active' %} bg-gradient-to-r to-sky-300 from-fuchsia-300 {% elif room.status == 'waiting' %} bg-fuchsia-200 {% else%} bg-gray-300 {% endif %}"
    ></div>

    <div class="p-5">
      <!-- topic -->
      <h3 class="mb-4 text-lg font-semibold text-indigo-800">
        ID: {{ room.uuid }}
      </h3>

      <!-- detail -->
      <div class="text-sm text-gray-800 leading-6">
        <b>Name: </b> {{ room.client }} <br />
        <div class="flex gap-1 text-sm">
          <b>Status: </b>
          <span
            class="w-auto flex gap-1 items-center p-2 {% if room.status == 'active' %} bg-indigo-200 text-indigo-700 {% elif room.status == 'waiting' %} bg-fuchsia-200 text-fuchsia-700 {% else%} bg-gray-200 text-gray-700 {% endif %} text-xs font-medium me-2 px-2.5 py-0.5 rounded-full"
          >
            <svg
              aria-hidden="true"
              class="{% if room.status == 'waiting' %} block {% else %} hidden {% endif %} inline w-3 h-3 text-gray-200 animate-spin fill-indigo-600"
              viewBox="0 0 100 101"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
                fill="currentColor"
              />
              <path
                d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
                fill="currentFill"
              />
            </svg>
            <p>{{ room.status }}</p>
          </span>
        </div>
        <b>Agent: </b> {% firstof room.agent.name '-' %} <br />
      </div>

      <!-- action -->
      <div class="w-full flex justify-between mt-2">
        <div class="w-full text-sm font-normal mt-3">
          <div
            class="grid grid-cols-2 gap-2 {% if room.status == 'closed' %} hidden {% endif %}"
          >
            <div>
              <a
                href="{%  url 'chat:room' room.uuid %}"
                class="flex gap-2 justify-center items-center w-full px-2 py-1.5 text-sm font-medium text-center text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl rounded-lg hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 transition-all duration-1000 group"
                >Join
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4 group-hover:translate-x-1 transition-all duration-500">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 8.25 21 12m0 0-3.75 3.75M21 12H3" />
                </svg>
              </a>
            </div>
            <div>
              <a
                href="{%  url 'chat:delete_room' room.uuid %}"
                class="inline-flex justify-center w-full px-2 py-1.5 text-sm font-medium text-center text-gray-900 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200"
                >Delete</a
              >
            </div>
          </div>
          <div
            class="grid grid-cols-2 gap-2 {% if room.status != 'closed' %} hidden {% endif %}"
          >
            <div>
              <a
                href="{%  url 'chat:delete_room' room.uuid %}"
                class="inline-flex justify-center w-full px-2 py-1.5 text-sm font-medium text-center text-gray-900 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200"
                >Delete</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>