chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("api/create-room/<str:uuid>/", views.create_room, name="create-room"),
    path("chat-admin/", views.admin, name="admin"),
    path("chat-admin/add-user/", views.add_user, name="add_user"),
    path("chat-admin/users/<uuid:uuid>/", views.user_detail, name="user_detail"),
    path("chat-admin/users/<uuid:uuid>/edit/", views.edit_user, name="edit_user"),
    path("chat-admin/<str:uuid>/", views.room, name="room"),
    path("chat-admin/<str:uuid>/delete/", views.delete_room, name="delete_room"),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),
]

jatte/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')

def contact(request):
    return render(request, 'core/contact.html')

core/templates/core/about.html
{% extends 'core/base.html' %} {% block content %}
<h1 class="mb-6 text-2xl"></h1>

<div
  class="absolute -z-20 circleposition w-[520px] h-[520px] rounded-full bg-fuchsia-400 blur-[90px]"
></div>
<div
  class="absolute -z-20 circleposition w-[400px] h-[400px] rounded-full bg-sky-300 blur-[90px] left-[30%]"
></div>
<div
  class="absolute -z-20 circleposition w-[500px] h-[500px] rounded-full bg-indigo-300 blur-[90px] left-[50%] top-[22%]"
></div>
<div
  class="absolute -z-20 circleposition w-[500px] h-[500px] rounded-full bg-fuchsia-200 blur-[90px] left-[40%] top-[24%]"
></div>

<div
  class="bg-white/65 backdrop-blur-[20px] py-16 px-4 rounded-2xl shadow-2xl shadow-violet-300 text-indigo-900"
>
  <div class="max-w-3xl mx-auto text-center">

    <h1 class="mb-3 text-3xl font-extrabold text-gray-900 md:text-3xl lg:text-4xl"><span class="text-transparent bg-clip-text bg-gradient-to-r to-sky-600 from-fuchsia-500">About</span> <span class="text-2xl font-semibold text-indigo-900">This Project </span></h1>

    <p class="mb-8 leading-relaxed">
      This is a real-time chat application built with Django, WebSockets (via
      Django Channels), and Tailwind CSS. It allows users to sign up, log in,
      and chat instantly in public or private rooms. Messages are sent and
      received without refreshing the page, providing a seamless and modern chat
      experience.
    </p>

    <div class="grid grid-cols-2 gap-4">
      <div
        class="bg-white/75 bg-opacity-10 p-7 rounded-xl shadow-md shadow-indigo-500"
      >
        <h2
          class="text-xl font-semibold mb-4 flex gap-2 justify-center items-center"
        >
          Key Features
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="violet"
            class="size-4"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25"
            />
          </svg>
        </h2>
        <ul class="list-disc list-inside text-left text-sm">
          <li>Real-time messaging with Django Channels</li>
          <li>Authentication (Login/Register)</li>
          <li>Multiple chat rooms</li>
          <li>Modern responsive UI using Tailwind CSS</li>
        </ul>
      </div>
      <div
        class="bg-white/75 bg-opacity-10 p-7 rounded-xl shadow-md shadow-indigo-500"
      >
        <h2 class="text-xl font-semibold mb-4 flex gap-2 justify-center items-center">
          Tech Stacks

          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="deepskyblue"
            class="size-4"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M9.75 3.104v5.714a2.25 2.25 0 0 1-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 0 1 4.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082M19.8 15.3l-1.57.393A9.065 9.065 0 0 1 12 15a9.065 9.065 0 0 0-6.23-.693L5 14.5m14.8.8 1.402 1.402c1.232 1.232.65 3.318-1.067 3.611A48.309 48.309 0 0 1 12 21c-2.773 0-5.491-.235-8.135-.687-1.718-.293-2.3-2.379-1.067-3.61L5 14.5"
            />
          </svg>
        </h2>
        <ul class="list-disc list-inside text-left text-sm">
          <li>Backend: Django, Django Channels</li>
          <li>Frontend: Tailwind CSS, flowbite, JavaScript</li>
          <li>Database: SQLite</li>
          <li>Authentication: Django authentication system</li>
        </ul>
      </div>
    </div>

    <div class="mt-10">
      <a
        href="https://github.com/ouyniya/django-real-time-chat-website"
        target="_blank"
        class="flex gap-2 justify-center items-center py-3 px-6 bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 text-white rounded-xl shadow-lg"
      >
        <svg
          height="32px"
          width="32px"
          version="1.1"
          id="Layer_1"
          xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          viewBox="0 0 291.32 291.32"
          xml:space="preserve"
          fill="#000000"
        >
          <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
          <g
            id="SVGRepo_tracerCarrier"
            stroke-linecap="round"
            stroke-linejoin="round"
          ></g>
          <g id="SVGRepo_iconCarrier">
            <g>
              <path
                style="fill: #ffffff"
                d="M145.66,0C65.219,0,0,65.219,0,145.66c0,80.45,65.219,145.66,145.66,145.66 s145.66-65.21,145.66-145.66C291.319,65.219,226.1,0,145.66,0z M186.462,256.625c-0.838-11.398-1.775-25.518-1.83-31.235 c-0.364-4.388-0.838-15.549-11.434-22.677c42.068-3.523,62.087-26.774,63.526-57.499c1.202-17.497-5.754-32.883-18.107-45.3 c0.628-13.282-0.401-29.023-1.256-35.941c-9.486-2.731-31.608,8.949-37.79,13.947c-13.037-5.062-44.945-6.837-64.336,0 c-13.747-9.668-29.396-15.64-37.926-13.974c-7.875,17.452-2.813,33.948-1.275,35.914c-10.142,9.268-24.289,20.675-20.447,44.572 c6.163,35.04,30.816,53.94,70.508,58.564c-8.466,1.73-9.896,8.048-10.606,10.788c-26.656,10.997-34.275-6.791-37.644-11.425 c-11.188-13.847-21.23-9.832-21.849-9.614c-0.601,0.218-1.056,1.092-0.992,1.511c0.564,2.986,6.655,6.018,6.955,6.263 c8.257,6.154,11.316,17.27,13.2,20.438c11.844,19.473,39.374,11.398,39.638,11.562c0.018,1.702-0.191,16.032-0.355,27.184 C64.245,245.992,27.311,200.2,27.311,145.66c0-65.365,52.984-118.348,118.348-118.348S264.008,80.295,264.008,145.66 C264.008,196.668,231.69,239.992,186.462,256.625z"
              ></path>
            </g>
          </g>
        </svg>
        <p class="text-xl font-semibold">View on GitHub</p>
      </a>
    </div>
  </div>
</div>

{% endblock %}

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/main.min.css' %}"
    />

    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css" rel="stylesheet">

  </head>

  <body class="font-sans text-gray-800">

    <div class="font-sans flex flex-col h-screen w-screen">

      <!-- Navbar -->
  <div class="font-sans w-screen text-[17px] px-[72px] py-[24px] flex justify-between items-center">
    <!-- Logo -->
    <div>
      <h1 class="flex gap-2 text-[36px] font-semibold w-1/3">
        <a href="{% url 'core:index' %}" class="flex gap-2 group">
          <span>
           Nys 
          </span>
           <span class="text-[#8a3bc3] group-hover:animate-bounce">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M15.042 21.672 13.684 16.6m0 0-2.51 2.225.569-9.47 5.227 7.917-3.286-.672ZM12 2.25V4.5m5.834.166-1.591 1.591M20.25 10.5H18M7.757 14.743l-1.59 1.59M6 10.5H3.75m4.007-4.243-1.59-1.59" />
            </svg>
          </span>
        </a>
      </h1>
    </div>
    <!-- Navigation -->
    <div class="w-4/5 flex justify-end text-right">
      <ul class="flex gap-[32px]">
        <li class="cursor-pointer hover:text-indigo-500 hover:-translate-y-0.5 transition-all"><a href="{% url 'core:index' %}">Home</a></li>
        <li class="cursor-pointer hover:text-indigo-500 hover:-translate-y-0.5 transition-all"><a href="{% url 'core:about' %}">About</a></li>
        <!-- <li class="cursor-pointer hover:text-indigo-500 hover:-translate-y-0.5 transition-all">Profile</li>
        <li class="cursor-pointer hover:text-indigo-500 hover:-translate-y-0.5 transition-all">Blog</li> -->

        {% if request.user.is_authenticated %}
        <li class="cursor-pointer">
          <a href="{% url 'chat:admin' %}" class="flex gap-1 hover:text-indigo-500 hover:-translate-y-0.5 transition-all duration-300">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-indigo-600 ">
              <path stroke-linecap="round" stroke-linejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 0 1 .865-.501 48.172 48.172 0 0 0 3.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0 0 12 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018Z" />
            </svg>
            Chat Admin
          </a>
        {% endif %}
        </li>

        <li class="cursor-pointer hover:text-indigo-500 hover:-translate-y-0.5 transition-all"><a href="{% url 'core:contact' %}">Contact us</a></li>
      </ul>
    </div>

    
  </div>
      <main class="mx-auto">
        {% if messages %}
        <div class="message mb-6 p-6 bg-gray-800 text-white rounded-xl">
          {% for message in messages %}
          <p>{{ message }}</p>
          {% endfor %}
        </div>
        {% endif %} 
        <div class="min-w-[1000px]">

          {% block content %} 
          {% endblock %}

        </div>
      </main>

    </div>


    {% block script %}
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
    {% endblock %}
  </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %} {% load static %} {% block content %}

<!-- Hero Section -->
<div class="w-screen flex-1 relative">
  <div
    class="h-[480px] bg-[url('https://images.unsplash.com/photo-1518288319310-99bc48891084?q=80&w=1472&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D')] bg-cover bg-right bg-no-repeat flex items-center text-white"
  >
    <div
      class="absolute w-full h-[480px] bg-indigo-900 bg-cover bg-right bg-no-repeat items-center text-white opacity-40"
    ></div>
    <div class="flex flex-col z-20 pl-[120px]">
      <div class="text-[34px] leading-8">Django</div>
      <div class="text-[56px] font-medium mb-4">Real-time Chat Website</div>
      <p class="w-[397px] mb-[40px]">
        We build a dynamic chat website by leveraging Django Channels to enable
        real-time communication.
      </p>
      <div class="flex gap-[16px]">
        <button class="rounded-[4px] p-[12px] bg-white font-medium text-black">
          Start Now
        </button>
        <button
          class="rounded-[4px] p-[12px] border-2 border-white text-white font-medium"
        >
          <a href="{% url 'chat:admin' %}"> Chat admin </a>
        </button>
      </div>
    </div>
  </div>
</div>

<section class="bg-white dark:bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16">
    <div class="grid md:grid-cols-2 gap-8">
      <div
        class="bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-8 md:p-12"
      >
        <a
          href="#"
          class="bg-green-100 text-green-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded-md dark:bg-gray-700 dark:text-green-400 mb-2"
        >
          <svg
            class="w-2.5 h-2.5 me-1.5"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 18 18"
          >
            <path
              d="M17 11h-2.722L8 17.278a5.512 5.512 0 0 1-.9.722H17a1 1 0 0 0 1-1v-5a1 1 0 0 0-1-1ZM6 0H1a1 1 0 0 0-1 1v13.5a3.5 3.5 0 1 0 7 0V1a1 1 0 0 0-1-1ZM3.5 15.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2ZM16.132 4.9 12.6 1.368a1 1 0 0 0-1.414 0L9 3.55v9.9l7.132-7.132a1 1 0 0 0 0-1.418Z"
            />
          </svg>
          Design
        </a>
        <h1
          class="mb-3 text-3xl font-extrabold text-gray-900 md:text-3xl lg:text-4xl"
        >
          <span
            class="text-transparent bg-clip-text bg-gradient-to-r to-sky-600 from-fuchsia-500"
            >General</span
          >
          Purpose
        </h1>
        <p class="text-lg font-normal text-gray-500 dark:text-gray-400 mb-4">
          In this exciting project, we build a dynamic chat website by
          leveraging Django Channels to enable real-time communication. Users
          can engage in live conversations with agents on the backend, providing
          an interactive platform.
        </p>
        <a
          href="#"
          class="text-blue-600 dark:text-blue-500 hover:underline font-medium text-lg inline-flex items-center"
          >Read more
          <svg
            class="w-3.5 h-3.5 ms-2 rtl:rotate-180"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 14 10"
          >
            <path
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M1 5h12m0 0L9 1m4 4L9 9"
            />
          </svg>
        </a>
      </div>
      <div
        class="bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-8 md:p-12"
      >
        <a
          href="#"
          class="bg-purple-100 text-purple-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded-md dark:bg-gray-700 dark:text-purple-400 mb-2"
        >
          <svg
            class="w-2.5 h-2.5 me-1.5"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 20 16"
          >
            <path
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M5 4 1 8l4 4m10-8 4 4-4 4M11 1 9 15"
            />
          </svg>
          Code
        </a>
        <h2 class="text-gray-900 dark:text-white text-3xl font-extrabold mb-2">
          Inspired by Code With Stein
        </h2>
        <p class="text-lg font-normal text-gray-500 dark:text-gray-400 mb-4">
          Special thanks to the creator for the detailed step-by-step guide on
          building this chat website using Django Channels and real-time
          communication techniques. Watch the full tutorial
          <a
            href="https://youtu.be/9e7CTR2Ya4Y?feature=shared"
            class="underline"
            >here</a
          >
        </p>
        <a
          href="#"
          class="text-blue-600 dark:text-blue-500 hover:underline font-medium text-lg inline-flex items-center"
          >Read more
          <svg
            class="w-3.5 h-3.5 ms-2 rtl:rotate-180"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 14 10"
          >
            <path
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M1 5h12m0 0L9 1m4 4L9 9"
            />
          </svg>
        </a>
      </div>
    </div>
  </div>
</section>

<!-- Icon section -->
<div
  class="mt-2 pb-8 px-[80px] grid grid-cols-3 gap-4 items-center max-w-7xl m-auto"
>
  <div class="text-center">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="w-12 h-12 mb-8 text-fuchsia-600 mx-auto"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25M9 16.5v.75m3-3v3M15 12v5.25m-4.5-15H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z"
      />
    </svg>

    <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

    <p class="text-gray-500">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan
      tortor at sem fermentum tempor.
    </p>
  </div>

  <div class="text-center">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="w-12 h-12 mb-8 text-violet-600 mx-auto"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"
      />
    </svg>

    <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

    <p class="text-gray-500">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan
      tortor at sem fermentum tempor.
    </p>
  </div>

  <div class="text-center">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="w-12 h-12 mb-8 text-blue-500 mx-auto"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 0 1 3 19.875v-6.75ZM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V8.625ZM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V4.125Z"
      />
    </svg>

    <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

    <p class="text-gray-500">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan
      tortor at sem fermentum tempor.
    </p>
  </div>
</div>

<!-- footer section -->

<footer
  class="fixed bottom-0 left-0 z-0 w-full p-4 bg-white border-t border-gray-200 shadow-sm md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800 dark:border-gray-600"
>
  <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400"
    >© 2025
    <a href="https://github.com/ouyniya" class="hover:underline">Nys</a>. All
    Rights Reserved.
  </span>
  <ul
    class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0"
  >
    <li>
      <a href="https://github.com/ouyniya" class="hover:underline me-4 md:me-6"
        >GitHub</a
      >
    </li>
    <li>
      <a href="#" class="hover:underline me-4 md:me-6">Privacy Policy</a>
    </li>
    <li>
      <a href="#" class="hover:underline me-4 md:me-6">Licensing</a>
    </li>
    <li>
      <a href="#" class="hover:underline">Contact</a>
    </li>
  </ul>
</footer>

{% include 'chat/partials/chat_bubble.html' %} {% endblock %}